#!/bin/bash
# android-mcp-orchestrator up.sh — build + start the ephemeral MCP stack.
#
# Off-by-default lifecycle: callers must pair every up.sh with down.sh (or use
# run.sh, which guarantees teardown via trap). The stack should NOT be left
# running between tasks.
#
# Usage: ./up.sh [--mock] [compose-dir]
#   --mock       also start the mock-synapse container (Matrix Synapse Manager testing)
#   compose-dir  override compose root (default: bundled <plugin>/infrastructure).
#                Positional only — exporting COMPOSE_DIR does not work here.
#
# Environment (read from the shell first, then <compose-dir>/.env, matching how
# compose itself resolves them):
#   APK_DIR         host dir mounted read-only at /apks. No working default: the
#                   fallback is relative to the compose dir (the bundled plugin
#                   dir), so set an absolute path to your project's
#                   app/build/outputs/apk/debug.
#   SCREENSHOT_DIR  host dir mounted at /screenshots. Same defaulting, but it is
#                   created if missing.
#
# Exit codes:
#   0 stack up   1 MCP never came up   2 no compose file   3 podman-compose
#   missing   4 APK_DIR does not exist   5 SCREENSHOT_DIR could not be created
#
# Requires:
#   - podman 4.x or 5.x
#   - podman-compose >= 1.1 (Ubuntu 24.04's apt podman-compose is 1.0.6 — it
#     lacks --profile support, so --mock won't work. Prefer `pipx install
#     podman-compose` to get 1.5.x.)
#
# Side effects:
#   - Creates <compose-dir>/.env with a random MCP_AUTH_TOKEN if it does not exist.
#   - Builds the compose images, but only when one or more required images are
#     missing from the local image store. To force a rebuild after editing a
#     Containerfile, `podman image rm` the affected image (or `podman compose
#     down --rmi local`) and re-run.
#   - Starts containers and waits for the MCP HTTP listener on 127.0.0.1:8000.

set -Eeuo pipefail

# --help before the provider lookup below: a machine missing podman-compose is
# exactly the machine whose owner is reading --help, and exiting 3 at them
# instead of printing usage is unhelpful.
if [ "${1:-}" = "--help" ] || [ "${1:-}" = "-h" ]; then
  # Print the leading comment block (everything after the shebang up to the
  # first non-comment line), stripping the leading "# ". Derived rather than a
  # hardcoded line range, so editing the header can't silently truncate --help.
  awk 'NR==1 {next} /^#/ {sub(/^# ?/, ""); print; next} {exit}' "$0"
  exit 0
fi

# Force `podman compose` to delegate to podman-compose (the python tool that
# drives the podman engine) and never to `docker compose`. Without this, on
# any machine where docker-compose-v2 is installed, podman 5.x will silently
# pick the docker plugin and run the entire stack against the Docker daemon
# — which means images live in Docker's store, not podman's, and our
# image-presence check below never matches anything (so builds run every
# time, on Docker, while pretending to be podman). Override only if the
# caller deliberately wants a different provider.
# Look up podman-compose: prefer the pipx-installed one (typically 1.5.0+,
# which supports `--profile`); fall back to /usr/bin (Ubuntu 24.04 ships
# 1.0.6, which does NOT support profiles — `--mock` will break).
if [ -z "${PODMAN_COMPOSE_PROVIDER:-}" ]; then
  for candidate in "$HOME/.local/bin/podman-compose" /usr/local/bin/podman-compose /usr/bin/podman-compose; do
    if [ -x "$candidate" ]; then
      PODMAN_COMPOSE_PROVIDER="$candidate"
      break
    fi
  done
fi
if [ -z "${PODMAN_COMPOSE_PROVIDER:-}" ] || [ ! -x "$PODMAN_COMPOSE_PROVIDER" ]; then
  echo "error: podman-compose not found (tried ~/.local/bin, /usr/local/bin, /usr/bin)" >&2
  echo "       install it with: pipx install podman-compose" >&2
  exit 3
fi
export PODMAN_COMPOSE_PROVIDER

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
# scripts/ -> skill/ -> skills/ -> plugin-root/infrastructure
DEFAULT_COMPOSE_DIR="$SCRIPT_DIR/../../../infrastructure"

MOCK=0
COMPOSE_DIR=""
for arg in "$@"; do
  case "$arg" in
    --mock) MOCK=1 ;;
    *)      COMPOSE_DIR="$arg" ;;
  esac
done
: "${COMPOSE_DIR:=$DEFAULT_COMPOSE_DIR}"

if [ ! -f "$COMPOSE_DIR/compose.yaml" ] && [ ! -f "$COMPOSE_DIR/docker-compose.yaml" ]; then
  echo "error: no compose file in $COMPOSE_DIR" >&2
  exit 2
fi

ENV_FILE="$COMPOSE_DIR/.env"
if [ ! -f "$ENV_FILE" ]; then
  echo "=== generating $ENV_FILE with a random MCP_AUTH_TOKEN ==="
  umask 077
  TOKEN="$(head -c 32 /dev/urandom | base64 | tr -d '/+=' | head -c 43)"
  {
    echo "# Auto-generated by up.sh — token authenticates loopback JSON-RPC calls"
    echo "# to the in-container MCP server. Safe to delete; will be regenerated."
    echo "MCP_AUTH_TOKEN=$TOKEN"
    echo
    echo "# Where the stack finds your APKs and writes screenshots. Both are"
    echo "# left COMMENTED OUT on purpose: uncommenting one adds a second place"
    echo "# the path is configured, alongside the compose default. Uncomment"
    echo "# only to override. A value in the shell environment still wins over"
    echo "# whatever is set here — that is the precedence compose itself uses."
    echo "#"
    echo "# The compose defaults shown below are relative to the compose"
    echo "# directory itself, which is this plugin's bundled infrastructure/"
    echo "# dir when the stack is launched via up.sh — NOT the project you are"
    echo "# testing. Set an absolute path here to point the stack at a project."
    echo "# APK_DIR=./app/build/outputs/apk/debug"
    echo "# SCREENSHOT_DIR=./play-screenshots"
    echo "#"
    echo "# Multi-repo layout — prefer absolute paths. Relative overrides are"
    echo "# resolved from this compose directory, so a checkout elsewhere under"
    echo "# your source root needs a surprising number of ../ segments and"
    echo "# breaks if the plugin is installed at a different depth:"
    echo "# APK_DIR=/absolute/path/to/your-project/app/build/outputs/apk/debug"
    echo "# SCREENSHOT_DIR=/absolute/path/to/your-project/play-screenshots"
  } >"$ENV_FILE"
  chmod 600 "$ENV_FILE"
fi

cd "$COMPOSE_DIR"

# Validate the host mount sources before compose can paper over them. Podman
# creates an EMPTY directory for a bind-mount source that does not exist, so a
# wrong APK_DIR otherwise surfaces as "no APK found" from inside the container,
# minutes later, instead of as an error here. Relative values are resolved
# against this directory — we validate after the `cd` above precisely so that
# resolution matches how compose itself will resolve them.
#
# Compose resolves ${VAR} from the shell environment FIRST and falls back to
# $ENV_FILE, so validating the shell environment alone would reject a path that
# compose would have mounted correctly — and .env is a documented, seeded place
# to set these. Mirror that precedence: fold in .env only for a variable the
# shell did not already provide. Read the two keys directly rather than sourcing
# the file, which would execute whatever it contains.
#
# `[ -v ]`, not `-z`: a variable exported as EMPTY counts as provided, and
# compose then ignores .env for it and falls through to the compose-file default
# (verified against `podman compose config`). Treating empty as absent here would
# validate the .env path while compose mounted the placeholder instead — the one
# direction that produces the silent empty mount this check exists to prevent.
if [ -f "$ENV_FILE" ]; then
  for _v in APK_DIR SCREENSHOT_DIR; do
    if ! [ -v "$_v" ]; then
      _line="$(grep -E "^${_v}=" "$ENV_FILE" | tail -n1 || true)"
      if [ -n "$_line" ]; then
        _val="${_line#*=}"
        # compose strips one layer of surrounding quotes; match that.
        _val="${_val%\"}"; _val="${_val#\"}"
        _val="${_val%\'}"; _val="${_val#\'}"
        [ -n "$_val" ] && export "$_v=$_val"
      fi
    fi
  done
  unset _v _line _val
fi

# These two defaults MIRROR the ones in compose.yaml's volumes block; that file
# is the source of truth. They are placeholders: relative to this bundled
# infrastructure/ dir, not to any project (see the plugin README, "Pointing the
# stack at your project"). Keep the pair in sync when either changes.
apk_dir="${APK_DIR:-./app/build/outputs/apk/debug}"
screenshot_dir="${SCREENSHOT_DIR:-./play-screenshots}"

# APK_DIR is an INPUT — it must already hold a built APK, so a missing dir is a
# hard error. Creating it would guarantee the empty-mount failure we are here to
# prevent.
if [ ! -d "$apk_dir" ]; then
  echo "error: APK directory does not exist: $apk_dir" >&2
  if [ -v APK_DIR ] && [ -z "$APK_DIR" ]; then
    # Diagnose with the same `[ -v ]` semantics the resolver above uses: an
    # exported-empty APK_DIR IS set, so saying it is unset would be false.
    echo "       APK_DIR is exported but empty. Compose treats that as set and" >&2
    echo "       ignores $ENV_FILE for it, falling through to the placeholder" >&2
    echo "       default resolved against $PWD. Give it a real absolute path, or" >&2
    echo "       unset it entirely to let $ENV_FILE apply." >&2
  elif ! [ -v APK_DIR ]; then
    echo "       APK_DIR is set neither in the environment nor in" >&2
    echo "       $ENV_FILE, so this is the placeholder default resolved against" >&2
    if [ "$COMPOSE_DIR" = "$DEFAULT_COMPOSE_DIR" ]; then
      echo "       $PWD — the bundled plugin dir, not your project." >&2
    else
      echo "       the compose dir you passed, $PWD — not your project unless" >&2
      echo "       that is where your APK lands." >&2
    fi
    echo "       Set APK_DIR to an absolute path holding your debug APK:" >&2
    echo "         APK_DIR=/path/to/project/app/build/outputs/apk/debug ./up.sh" >&2
    echo "       or uncomment APK_DIR in $ENV_FILE." >&2
  else
    echo "       APK_DIR is set to '$APK_DIR'. Build the app first (./gradlew" >&2
    echo "       assembleDebug), or correct the path. Note that a relative value" >&2
    echo "       resolves against $PWD, so prefer an absolute path." >&2
  fi
  exit 4   # 4 = misconfigured input path
fi

# SCREENSHOT_DIR is an OUTPUT — creating it is correct, and matches the
# documented `mkdir -p` step it replaces. Only a genuine failure to create it
# (bad path, no permission) is an error.
if [ ! -d "$screenshot_dir" ]; then
  echo "=== creating screenshot output dir: $screenshot_dir ==="
  if ! mkdir -p "$screenshot_dir"; then
    echo "error: could not create screenshot directory: $screenshot_dir" >&2
    echo "       Set SCREENSHOT_DIR to a writable absolute path." >&2
    exit 5   # 5 = output dir could not be created (distinct from 4 so wrappers
             #     can tell "wrong project" from "permissions/disk")
  fi
fi

# Skip-build guard: podman compose build always re-walks every Containerfile
# (slow, noisy) even on a full cache hit. Skip the build entirely when every
# image the active profile needs is already present locally. To force a rebuild
# after editing a Containerfile or bumping a pinned version, `podman image rm`
# the relevant image and re-run, or delete all of them with
# `podman compose down --rmi local`.
#
# Image naming follows podman-compose 1.x: `localhost/<project>_<service>:latest`.
# Project name is the compose-dir basename ("infrastructure" by default).
PROJECT="$(basename "$PWD")"
REQUIRED_SERVICES=(android-mcp emulator-phone6in emulator-tablet7in emulator-tablet10in)
if [ "$MOCK" -eq 1 ]; then
  REQUIRED_SERVICES+=(mock-synapse)
fi

missing=0
for svc in "${REQUIRED_SERVICES[@]}"; do
  img="localhost/${PROJECT}_${svc}:latest"
  if ! podman image exists "$img"; then
    echo "=== image missing: $img ==="
    missing=1
  fi
done

if [ "$missing" -eq 1 ]; then
  echo "=== building MCP stack in $(pwd) ==="
  podman compose build
else
  echo "=== all required images present, skipping build ==="
fi

if [ "$MOCK" -eq 1 ]; then
  echo "=== starting with --profile mock ==="
  podman compose --profile mock up -d
else
  echo "=== starting (no mock) ==="
  podman compose up -d
fi

echo "=== waiting for MCP on http://127.0.0.1:8000/mcp (expect 401/405 when ready) ==="
# 401 = listener up, auth required (expected without bearer header). 405 = method-not-allowed
# from the GET-without-body path. Either confirms the listener is reachable.
# Boot + MCP startup: ~60-120s first run, ~30-60s subsequent.
for i in $(seq 1 60); do
  code=$(curl -s -o /dev/null -w '%{http_code}' --max-time 3 http://127.0.0.1:8000/mcp || echo "000")
  case "$code" in
    200|401|405)
      echo "MCP is up (HTTP $code) after ~$((i*10))s"
      exit 0
      ;;
  esac
  sleep 10
done
echo "error: MCP did not come up within 600s" >&2
exit 1
