#!/bin/bash
# android-mcp-orchestrator up.sh — build + start the ephemeral MCP stack.
#
# Off-by-default lifecycle: callers must pair every up.sh with down.sh (or use
# run.sh, which guarantees teardown via trap). The stack should NOT be left
# running between tasks.
#
# Usage: ./up.sh [--mock] [compose-dir]
#   --mock       also start the mock-synapse container (Matrix Synapse Manager testing)
#   compose-dir  override compose root (default: bundled <plugin>/infrastructure)
#
# Side effects:
#   - Creates <compose-dir>/.env with a random MCP_AUTH_TOKEN if it does not exist.
#   - Builds the compose images (idempotent).
#   - Starts containers and waits for the MCP HTTP listener on 127.0.0.1:8000.

set -Eeuo pipefail

if [ "${1:-}" = "--help" ] || [ "${1:-}" = "-h" ]; then
  sed -n '2,16p' "$0" | sed 's/^# \{0,1\}//'
  exit 0
fi

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
# scripts/ -> skill/ -> skills/ -> plugin-root/infrastructure
DEFAULT_COMPOSE_DIR="$SCRIPT_DIR/../../../infrastructure"

MOCK=0
COMPOSE_DIR=""
for arg in "$@"; do
  case "$arg" in
    --mock) MOCK=1 ;;
    *)      COMPOSE_DIR="$arg" ;;
  esac
done
: "${COMPOSE_DIR:=$DEFAULT_COMPOSE_DIR}"

if [ ! -f "$COMPOSE_DIR/compose.yaml" ] && [ ! -f "$COMPOSE_DIR/docker-compose.yaml" ]; then
  echo "error: no compose file in $COMPOSE_DIR" >&2
  exit 2
fi

ENV_FILE="$COMPOSE_DIR/.env"
if [ ! -f "$ENV_FILE" ]; then
  echo "=== generating $ENV_FILE with a random MCP_AUTH_TOKEN ==="
  umask 077
  TOKEN="$(head -c 32 /dev/urandom | base64 | tr -d '/+=' | head -c 43)"
  {
    echo "# Auto-generated by up.sh — token authenticates loopback JSON-RPC calls"
    echo "# to the in-container MCP server. Safe to delete; will be regenerated."
    echo "MCP_AUTH_TOKEN=$TOKEN"
  } >"$ENV_FILE"
  chmod 600 "$ENV_FILE"
fi

cd "$COMPOSE_DIR"
echo "=== building MCP stack in $(pwd) ==="
podman compose build

if [ "$MOCK" -eq 1 ]; then
  echo "=== starting with --profile mock ==="
  podman compose --profile mock up -d
else
  echo "=== starting (no mock) ==="
  podman compose up -d
fi

echo "=== waiting for MCP on http://127.0.0.1:8000/mcp (expect 401/405 when ready) ==="
# 401 = listener up, auth required (expected without bearer header). 405 = method-not-allowed
# from the GET-without-body path. Either confirms the listener is reachable.
# Boot + MCP startup: ~60-120s first run, ~30-60s subsequent.
for i in $(seq 1 60); do
  code=$(curl -s -o /dev/null -w '%{http_code}' --max-time 3 http://127.0.0.1:8000/mcp || echo "000")
  case "$code" in
    200|401|405)
      echo "MCP is up (HTTP $code) after ~$((i*10))s"
      exit 0
      ;;
  esac
  sleep 10
done
echo "error: MCP did not come up within 600s" >&2
exit 1
