#!/usr/bin/env bash
# Canonical test runner for this repo — every suite, regardless of language.
#
# Why this exists: the repo's suites live in five homes and two languages, and the
# invocation that plans used to carry in their Preflight block globbed only
# `planning/skills/*/tests/test-*.py scripts/tests/test-*.py`. That glob cannot see a
# bash suite, so `android-dev/skills/android-mcp-orchestrator/scripts/tests/test-mount-validation.sh`
# was silently skipped by anyone running "the suite" locally. Discovery here is by
# filename over the whole tree rather than by an enumerated list of directories, so a
# suite added in a new home or a new language is picked up without editing this file.
#
# Usage:
#   bash scripts/run-tests.sh          run every suite, then every validator
#   bash scripts/run-tests.sh --list   print discovered suite paths, run nothing
#
# --list prints suites only (the test-*.py / test-*.sh set). Validators are discovered
# separately: they are checks over the tree rather than test suites, so counting them as
# suites would make the discovery contract in
# scripts/tests/test-run-tests-discovery.py compare two different sets.
#
# Precisely what "a new language is picked up" means: it is FLAGGED, not run. A suite in
# an unsupported language hard-fails this runner with its name; adding an interpreter to
# run_one() is what makes it execute. The guarantee is "never silently skipped", not
# "runs anything".
#
# Exit 0 only when every suite and every validator passed.
set -uo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO" || exit 1

# Checks over the tree, not test suites. Run after the suites, reported the same way.
#
# DISCOVERED, not enumerated. An earlier cut hardcoded a single entry here while four
# other tree-wide guards existed — including check-usage-tokens.py, the very guard this
# repo added to catch stale docs. That is BL-020's defect (an enumerated list that
# silently omits members) reproduced inside BL-020's own fix, in the half nobody
# generalized. `scripts/check-*.py` is the repo's naming convention for a bare-runnable
# tree check; build-capability-index.py is deliberately excluded because it GENERATES
# rather than checks. Out-of-tree validators that do not follow the convention are
# listed explicitly below.
EXTRA_VALIDATORS=(
  "planning/skills/dispatching-parallel-agents/scripts/validate-stack-routing.py"
)

discover_validators() {
  { find ./scripts -maxdepth 1 -name 'check-*.py' -print | sed 's|^\./||'
    printf '%s\n' "${EXTRA_VALIDATORS[@]}"
  } | sort
}

# find's exit status must survive the pipeline. `mapfile -t X < <(fn)` reports
# mapfile's own read, NOT fn's — so an unreadable subtree makes find skip suites,
# print "Permission denied", and still leave the runner at exit 0 with a smaller
# SUITES array. The empty-glob guard cannot catch that: the array is short, not
# empty. A silently dropped suite is BL-020's defect reached by a third route, so
# discovery writes find's real status to $FIND_RC for the caller to check.
FIND_RC=""

discover() {
  local rc_file="$1"
  { find . -path ./node_modules -prune -o -path ./.git -prune -o \
         \( -name 'test-*.py' -o -name 'test-*.sh' \) -print; echo "$?" > "$rc_file"; } \
    | sed 's|^\./||' \
    | sort
}

# Extensions that are legitimately NOT test suites despite a test-* name: prose,
# data and generated bytecode. Everything else named test-* is treated as a suite,
# so an extension this runner has never been told about is surfaced rather than
# guessed at.
NON_SUITE_EXTS=(md markdown json yaml yml txt toml pyc lock)

# A suite written in a language this runner cannot execute must FAIL, never be
# skipped. Silently ignoring it is precisely BL-020 in a new language: the bash
# suite was invisible to a python-only glob and nobody noticed for weeks.
#
# This sweep spans the WHOLE tree, matching discover()'s scope. An earlier cut
# restricted it to */tests/* while discovery walked everything, so a suite that was
# BOTH in a new home and in a new language (newplugin/scripts/test-x.rb) fell through
# the gap between the two scopes and the runner exited 0. The two scopes must match or
# the difference between them is exactly where a suite goes unrun.
unsupported() {
  local rc_file="$1"
  local prune_exts=()
  for e in "${NON_SUITE_EXTS[@]}"; do prune_exts+=(! -name "*.$e"); done
  { find . -path ./node_modules -prune -o -path ./.git -prune -o \
         -path '*/__pycache__' -prune -o -path '*/test-fixtures/*' -prune -o \
         -type f -name 'test-*' \
         ! -name '*.py' ! -name '*.sh' "${prune_exts[@]}" -print; echo "$?" > "$rc_file"; } \
    | sed 's|^\./||' \
    | sort
}

RC_DIR="$(mktemp -d)"
trap 'rm -rf "$RC_DIR"' EXIT
mapfile -t SUITES < <(discover "$RC_DIR/suites.rc")
mapfile -t UNSUPPORTED < <(unsupported "$RC_DIR/unsupported.rc")

for scan in suites unsupported; do
  rc="$(cat "$RC_DIR/$scan.rc" 2>/dev/null || echo 1)"
  if [ "$rc" != "0" ]; then
    echo "FAIL: the $scan scan could not read the whole tree (find exit $rc)." >&2
    echo "Some suites may be missing from this run; refusing to report a pass." >&2
    exit 1
  fi
done

if [ "${#UNSUPPORTED[@]}" -ne 0 ]; then
  echo "FAIL: ${#UNSUPPORTED[@]} suite file(s) in a language this runner cannot run:" >&2
  printf '  %s\n' "${UNSUPPORTED[@]}" >&2
  echo "Supported suite extensions: .py, .sh." >&2
  echo "Either add an interpreter to run_one() in $0, or — if this is fixture DATA and" >&2
  echo "not a suite — rename it so it does not start with 'test-'." >&2
  exit 1
fi

# An empty sweep must never read as a pass — the same rule validate-plan-progress.yml
# states in its own words ("the glob is wrong, not the tree"). A runner that finds
# nothing and exits 0 is worse than no runner: it reports success for zero coverage.
if [ "${#SUITES[@]}" -eq 0 ]; then
  echo "FAIL: discovered 0 test suites under $REPO — the discovery glob is wrong, not the tree." >&2
  exit 1
fi

if [ "${1:-}" = "--list" ]; then
  if [ "$#" -gt 1 ]; then
    echo "FAIL: --list takes no further arguments (got '$2')" >&2
    exit 1
  fi
  printf '%s\n' "${SUITES[@]}"
  exit 0
fi

if [ "$#" -gt 0 ]; then
  echo "FAIL: unknown argument '$1' (accepts no arguments, or --list)" >&2
  exit 1
fi

failed=()

run_one() {
  local path="$1"
  case "$path" in
    *.py) python3 "$path" ;;
    *.sh) bash "$path" ;;
    *)
      # Unreachable via discover(), which only emits .py/.sh — kept as a guard so
      # adding an extension to discover() without adding an interpreter here fails
      # loudly instead of running nothing.
      echo "FAIL: $path has no known interpreter (expected .py or .sh)" >&2
      return 1
      ;;
  esac
}

echo "Running ${#SUITES[@]} suite(s):"
for suite in "${SUITES[@]}"; do
  echo "== $suite"
  if ! run_one "$suite" > /dev/null 2>&1; then
    # Re-run visibly so the failure output is the last thing on screen, not swallowed.
    echo "-- FAILED, re-running with output:"
    run_one "$suite"
    failed+=("$suite")
  fi
done

mapfile -t VALIDATORS < <(discover_validators)
echo "Running ${#VALIDATORS[@]} validator(s):"
for validator in "${VALIDATORS[@]}"; do
  echo "== $validator"
  if [ ! -f "$validator" ]; then
    echo "FAIL: validator $validator does not exist" >&2
    failed+=("$validator")
    continue
  fi
  if ! python3 "$validator" > /dev/null 2>&1; then
    echo "-- FAILED, re-running with output:"
    python3 "$validator"
    failed+=("$validator")
  fi
done

if [ "${#failed[@]}" -ne 0 ]; then
  echo
  echo "FAIL: ${#failed[@]} of $(( ${#SUITES[@]} + ${#VALIDATORS[@]} )) checks failed:" >&2
  printf '  %s\n' "${failed[@]}" >&2
  exit 1
fi

echo
echo "OK — ${#SUITES[@]} suite(s) and ${#VALIDATORS[@]} validator(s) passed."
