#!/usr/bin/env python3
"""Render `global-security.md` from security-scan.py's JSON on stdin.

Worst-first ordering: open CRITICAL desc, then HIGH, then staleness. The point of
the dashboard is the first row.

Two rendering rules carry the whole honesty of this layer:

  * **An unrecorded count renders `?`, never `0`.** `0` means "measured, clean";
    `?` means "not measured". Collapsing them would let a never-measured project
    sit in the dashboard looking green.
  * **A `feeds` run is labelled.** It re-checked dependency advisories without
    running a single code lane, so its counts are carried forward, not
    re-verified. Presenting it as an audit would overstate what is known.
"""
import json
import sys

TREND = {"up": "▲", "down": "▼", "flat": "→"}


def num(v):
    return "?" if v is None else str(v)


def _sort_key(p):
    # None sorts last within its severity band: unknown is not "clean".
    c = p.get("critical"); h = p.get("high"); age = p.get("age_days")
    return (-(c if isinstance(c, int) else -1),
            -(h if isinstance(h, int) else -1),
            -(age if isinstance(age, int) else -1))


def render(doc):
    projects = doc.get("projects") or []
    audited = [p for p in projects if not p.get("never_audited")]
    never = [p for p in projects if p.get("never_audited")]
    audited.sort(key=_sort_key)

    crit_total = sum(p["critical"] for p in audited if isinstance(p.get("critical"), int))
    unmeasured = [p for p in audited if p.get("critical") is None]
    at_risk = [p for p in audited if isinstance(p.get("critical"), int) and p["critical"] > 0]

    L = ["# Global security", "",
         f"**Last rebuilt:** {doc.get('generated', '?')}", "",
         f"{len(audited)} audited project(s), {len(never)} never audited. "
         f"{len(at_risk)} with open CRITICALs ({crit_total} total).", ""]
    if unmeasured:
        L += [f"> {len(unmeasured)} audited project(s) did not record severity "
              f"counts — shown as `?`, which is **not** the same as clean.", ""]
    if not audited:
        L += ["_No project has a `security/history.jsonl` yet — nothing has been "
              "audited by sec-audit v1.29+._", ""]
    else:
        L += ["| Project | Last audit | Age | Mode | CRIT | HIGH | Open | Accepted | Trend |",
              "|---------|-----------|----:|------|-----:|-----:|-----:|---------:|:-----:|"]
        for p in audited:
            age = p.get("age_days")
            mode = p.get("mode") or "?"
            # A feed-only run did not look at the code — say so in the cell.
            if not p.get("code_verified"):
                mode = f"{mode} ⚠"
            L.append(
                f"| `{p['area']}/{p['name']}` | {p.get('last_run_id') or '?'} | "
                f"{'?' if age is None else str(age) + 'd'} | {mode} | "
                f"{num(p.get('critical'))} | {num(p.get('high'))} | "
                f"{num(p.get('total_open'))} | {num(p.get('accepted'))} | "
                f"{TREND.get(p.get('trend'), '·')} |")
        L.append("")
        if any(not p.get("code_verified") for p in audited):
            L += ["⚠ = the newest run was **feed-only**: dependency advisories were "
                  "re-checked but no code lane ran, so these counts are carried "
                  "forward, not re-verified.", ""]
        L += ["`Open` counts every open finding **including** accepted ones; "
              "\"open and not currently suppressed\" is `Open − Accepted`. "
              "`?` means the run did not record that number.", ""]

    if never:
        L += ["## Never audited", ""]
        for p in sorted(never, key=lambda x: (x["area"], x["name"])):
            note = f" — {p['note']}" if p.get("note") else ""
            L.append(f"- `{p['area']}/{p['name']}`{note}")
        L.append("")

    malformed = [p for p in audited if p.get("malformed_lines")]
    if malformed:
        L += ["## History problems", ""]
        for p in malformed:
            L.append(f"- `{p['area']}/{p['name']}` — {p['malformed_lines']} "
                     f"malformed line(s) in history.jsonl (skipped)")
        L.append("")

    if doc.get("couldnt_assess"):
        L += ["## Could not assess", ""]
        for c in doc["couldnt_assess"]:
            L.append(f"- `{c.get('area')}/{c.get('name')}` — {c.get('reason')}")
        L.append("")

    L += ["---", "",
          "_Generated by `planning/skills/portfolio/scripts/security-rollup.py` "
          "from each project's `security/history.jsonl` (sec-audit v1.29+). "
          "Do not edit by hand._", ""]
    return "\n".join(L)


def main():
    try:
        doc = json.load(sys.stdin)
    except (json.JSONDecodeError, ValueError) as e:
        sys.exit(f"security-rollup: input is not valid JSON ({e})")
    if not isinstance(doc, dict):
        sys.exit("security-rollup: expected a JSON object from security-scan.py")
    sys.stdout.write(render(doc))
    return 0


if __name__ == "__main__":
    sys.exit(main())
